# Generated by Django 2.2.1 on 2019-05-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190513_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='advance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
