# Generated by Django 2.2.1 on 2019-05-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
